//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using Findx.Data;
using FreeSql.DataAnnotations;
using System;

namespace Findx.Module.Admin.Models
{
    /// <summary>
    /// 系统用户表
    /// </summary>
    [Table(Name = "sys_user")]
    public partial class SysUserInfo : EntityBase<long>, IFullAudited<long>, IResponse, IRequest
    {

        /// <summary>
        /// 主键
        /// </summary>
        [Column(Name = "id", IsPrimary = true)]
        public override long Id { get; set; }

        /// <summary>
        /// 账号
        /// </summary>
        [Column(Name = "account", DbType = "varchar(50)")]
        public string Account { get; set; }

        /// <summary>
        /// 管理员类型（1超级管理员 2非管理员）
        /// </summary>
        [Column(Name = "admin_type", DbType = "tinyint(4)")]
        public int AdminType { get; set; }

        /// <summary>
        /// 头像
        /// </summary>
        [Column(Name = "avatar")]
        public long? Avatar { get; set; }

        /// <summary>
        /// 生日
        /// </summary>
        [Column(Name = "birthday", DbType = "date")]
        public DateTime? Birthday { get; set; }

        /// <summary>
        /// 邮箱
        /// </summary>
        [Column(Name = "email", DbType = "varchar(50)")]
        public string Email { get; set; }

        /// <summary>
        /// 最后登陆IP
        /// </summary>
        [Column(Name = "last_login_ip", DbType = "varchar(100)")]
        public string LastLoginIp { get; set; }

        /// <summary>
        /// 最后登陆时间
        /// </summary>
        [Column(Name = "last_login_time", DbType = "datetime")]
        public DateTime? LastLoginTime { get; set; }

        /// <summary>
        /// 姓名
        /// </summary>
        [Column(Name = "name", DbType = "varchar(100)")]
        public string Name { get; set; }

        /// <summary>
        /// 昵称
        /// </summary>
        [Column(Name = "nick_name", DbType = "varchar(50)")]
        public string NickName { get; set; }

        /// <summary>
        /// 密码
        /// </summary>
        [Column(Name = "password", DbType = "varchar(100)")]
        public string Password { get; set; }

        /// <summary>
        /// 手机
        /// </summary>
        [Column(Name = "phone", DbType = "varchar(50)")]
        public string Phone { get; set; }

        /// <summary>
        /// 性别(字典 1男 2女 3未知)
        /// </summary>
        [Column(Name = "sex", DbType = "tinyint(4)")]
        public int Sex { get; set; }

        /// <summary>
        /// 状态（字典 0正常 1冻结 2删除）
        /// </summary>
        [Column(Name = "status", DbType = "tinyint(4)")]
        public int Status { get; set; }

        /// <summary>
        /// 电话
        /// </summary>
        [Column(Name = "tel", DbType = "varchar(50)")]
        public string Tel { get; set; }

        /// <summary>
        /// 创建人
        /// </summary>
        [Column(Name = "create_user")]
        public long? CreatorId { get; set; }

        /// <summary>
        /// 创建时间
        /// </summary>
        [Column(Name = "create_time", DbType = "datetime")]
        public DateTime? CreatedTime { get; set; }

        /// <summary>
        /// 修改人
        /// </summary>
        [Column(Name = "update_user")]
        public long? LastUpdaterId { get; set; }

        /// <summary>
        /// 最后更新时间
        /// </summary>
        [Column(Name = "update_time", DbType = "datetime")]
        public DateTime? LastUpdatedTime { get; set; }
    }
}
