//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 中国行政地区表
	/// </summary>
	[SugarTable("sys_area")]
	public class SysAreaInfo {

		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public ulong Id { get; set; }

		/// <summary>
		/// 行政代码
		/// </summary>
		[SugarColumn(ColumnName ="area_code")]
		public string AreaCode { get; set; }

		/// <summary>
		/// 区号
		/// </summary>
		[SugarColumn(ColumnName ="city_code")]
		public string CityCode { get; set; }

		/// <summary>
		/// 纬度
		/// </summary>
		[SugarColumn(ColumnName ="lat")]
		public decimal? Lat { get; set; }

		/// <summary>
		/// 层级
		/// </summary>
		[SugarColumn(ColumnName ="level_code")]
		public byte? LevelCode { get; set; }

		/// <summary>
		/// 经度
		/// </summary>
		[SugarColumn(ColumnName ="lng")]
		public decimal? Lng { get; set; }

		/// <summary>
		/// 组合名
		/// </summary>
		[SugarColumn(ColumnName ="merger_name")]
		public string MergerName { get; set; }

		/// <summary>
		/// 名称
		/// </summary>
		[SugarColumn(ColumnName ="name")]
		public string Name { get; set; }

		/// <summary>
		/// 父级行政代码
		/// </summary>
		[SugarColumn(ColumnName ="parent_code")]
		public string ParentCode { get; set; }

		/// <summary>
		/// 拼音
		/// </summary>
		[SugarColumn(ColumnName ="pinyin")]
		public string Pinyin { get; set; }

		/// <summary>
		/// 简称
		/// </summary>
		[SugarColumn(ColumnName ="short_name")]
		public string ShortName { get; set; }

		/// <summary>
		/// 邮政编码
		/// </summary>
		[SugarColumn(ColumnName ="zip_code")]
		public string ZipCode { get; set; }

	}

}
