//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 代码生成基础配置
	/// </summary>
	[SugarTable("sys_code_generate")]
	public class SysCodeGenerateInfo {

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public long Id { get; set; }

		/// <summary>
		/// 作者姓名
		/// </summary>
		[SugarColumn(ColumnName ="author_name")]
		public string AuthorName { get; set; }

		/// <summary>
		/// 业务名
		/// </summary>
		[SugarColumn(ColumnName ="bus_name")]
		public string BusName { get; set; }

		/// <summary>
		/// 类名
		/// </summary>
		[SugarColumn(ColumnName ="class_name")]
		public string ClassName { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[SugarColumn(ColumnName ="create_time")]
		public DateTime? CreateTime { get; set; }

		/// <summary>
		/// 创建人
		/// </summary>
		[SugarColumn(ColumnName ="create_user")]
		public long? CreateUser { get; set; }

		/// <summary>
		/// 生成位置类型
		/// </summary>
		[SugarColumn(ColumnName ="generate_type")]
		public string GenerateType { get; set; }

		/// <summary>
		/// 包名称
		/// </summary>
		[SugarColumn(ColumnName ="package_name")]
		public string PackageName { get; set; }

		/// <summary>
		/// 功能名
		/// </summary>
		[SugarColumn(ColumnName ="table_comment")]
		public string TableComment { get; set; }

		/// <summary>
		/// 数据库表名
		/// </summary>
		[SugarColumn(ColumnName ="table_name")]
		public string TableName { get; set; }

		/// <summary>
		/// 是否移除表前缀
		/// </summary>
		[SugarColumn(ColumnName ="table_prefix")]
		public string TablePrefix { get; set; }

		/// <summary>
		/// 更新时间
		/// </summary>
		[SugarColumn(ColumnName ="update_time")]
		public DateTime? UpdateTime { get; set; }

		/// <summary>
		/// 更新人
		/// </summary>
		[SugarColumn(ColumnName ="update_user")]
		public long? UpdateUser { get; set; }

	}

}
