//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 代码生成详细配置
	/// </summary>
	[SugarTable("sys_code_generate_config")]
	public class SysCodeGenerateConfigInfo {

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public long Id { get; set; }

		/// <summary>
		/// 代码生成主表ID
		/// </summary>
		[SugarColumn(ColumnName ="code_gen_id")]
		public long? CodeGenId { get; set; }

		/// <summary>
		/// 字段描述
		/// </summary>
		[SugarColumn(ColumnName ="column_comment")]
		public string ColumnComment { get; set; }

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(ColumnName ="column_key")]
		public string ColumnKey { get; set; }

		/// <summary>
		/// 主外键名称
		/// </summary>
		[SugarColumn(ColumnName ="column_key_name")]
		public string ColumnKeyName { get; set; }

		/// <summary>
		/// 数据库字段名
		/// </summary>
		[SugarColumn(ColumnName ="column_name")]
		public string ColumnName { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[SugarColumn(ColumnName ="create_time")]
		public DateTime? CreateTime { get; set; }

		/// <summary>
		/// 创建人
		/// </summary>
		[SugarColumn(ColumnName ="create_user")]
		public long? CreateUser { get; set; }

		/// <summary>
		/// 物理类型
		/// </summary>
		[SugarColumn(ColumnName ="data_type")]
		public string DataType { get; set; }

		/// <summary>
		/// 字典code
		/// </summary>
		[SugarColumn(ColumnName ="dict_type_code")]
		public string DictTypeCode { get; set; }

		/// <summary>
		/// 作用类型（字典）
		/// </summary>
		[SugarColumn(ColumnName ="effect_type")]
		public string EffectType { get; set; }

		/// <summary>
		/// java类字段名
		/// </summary>
		[SugarColumn(ColumnName ="java_name")]
		public string JavaName { get; set; }

		/// <summary>
		/// java类型
		/// </summary>
		[SugarColumn(ColumnName ="java_type")]
		public string JavaType { get; set; }

		/// <summary>
		/// 查询方式
		/// </summary>
		[SugarColumn(ColumnName ="query_type")]
		public string QueryType { get; set; }

		/// <summary>
		/// 是否是查询条件
		/// </summary>
		[SugarColumn(ColumnName ="query_whether")]
		public string QueryWhether { get; set; }

		/// <summary>
		/// 修改时间
		/// </summary>
		[SugarColumn(ColumnName ="update_time")]
		public DateTime? UpdateTime { get; set; }

		/// <summary>
		/// 修改人
		/// </summary>
		[SugarColumn(ColumnName ="update_user")]
		public long? UpdateUser { get; set; }

		/// <summary>
		/// 增改
		/// </summary>
		[SugarColumn(ColumnName ="whether_add_update")]
		public string WhetherAddUpdate { get; set; }

		/// <summary>
		/// 是否是通用字段
		/// </summary>
		[SugarColumn(ColumnName ="whether_common")]
		public string WhetherCommon { get; set; }

		/// <summary>
		/// 是否必填（字典）
		/// </summary>
		[SugarColumn(ColumnName ="whether_required")]
		public string WhetherRequired { get; set; }

		/// <summary>
		/// 列表是否缩进（字典）
		/// </summary>
		[SugarColumn(ColumnName ="whether_retract")]
		public string WhetherRetract { get; set; }

		/// <summary>
		/// 列表展示
		/// </summary>
		[SugarColumn(ColumnName ="whether_table")]
		public string WhetherTable { get; set; }

	}

}
