//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 系统参数配置表
	/// </summary>
	[SugarTable("sys_config")]
	public class SysConfigInfo {

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public long Id { get; set; }

		/// <summary>
		/// 编码
		/// </summary>
		[SugarColumn(ColumnName ="code")]
		public string Code { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[SugarColumn(ColumnName ="create_time")]
		public DateTime? CreateTime { get; set; }

		/// <summary>
		/// 创建人
		/// </summary>
		[SugarColumn(ColumnName ="create_user")]
		public long? CreateUser { get; set; }

		/// <summary>
		/// 常量所属分类的编码，来自于“常量的分类”字典
		/// </summary>
		[SugarColumn(ColumnName ="group_code")]
		public string GroupCode { get; set; }

		/// <summary>
		/// 名称
		/// </summary>
		[SugarColumn(ColumnName ="name")]
		public string Name { get; set; }

		/// <summary>
		/// 备注
		/// </summary>
		[SugarColumn(ColumnName ="remark")]
		public string Remark { get; set; }

		/// <summary>
		/// 状态（字典 0正常 1停用 2删除）
		/// </summary>
		[SugarColumn(ColumnName ="status")]
		public sbyte Status { get; set; }

		/// <summary>
		/// 是否是系统参数（Y-是，N-否）
		/// </summary>
		[SugarColumn(ColumnName ="sys_flag")]
		public string SysFlag { get; set; }

		/// <summary>
		/// 更新时间
		/// </summary>
		[SugarColumn(ColumnName ="update_time")]
		public DateTime? UpdateTime { get; set; }

		/// <summary>
		/// 更新人
		/// </summary>
		[SugarColumn(ColumnName ="update_user")]
		public long? UpdateUser { get; set; }

		/// <summary>
		/// 值
		/// </summary>
		[SugarColumn(ColumnName ="value")]
		public string Value { get; set; }

	}

}
