//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 员工附属机构岗位表
	/// </summary>
	[SugarTable("sys_emp_ext_org_pos")]
	public class SysEmpExtOrgPosInfo {

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public long Id { get; set; }

		/// <summary>
		/// 员工id
		/// </summary>
		[SugarColumn(ColumnName ="emp_id")]
		public long EmpId { get; set; }

		/// <summary>
		/// 机构id
		/// </summary>
		[SugarColumn(ColumnName ="org_id")]
		public long OrgId { get; set; }

		/// <summary>
		/// 岗位id
		/// </summary>
		[SugarColumn(ColumnName ="pos_id")]
		public long PosId { get; set; }

	}

}
