//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 员工表
	/// </summary>
	[SugarTable("sys_emp")]
	public class SysEmpInfo {

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public long Id { get; set; }

		/// <summary>
		/// 工号
		/// </summary>
		[SugarColumn(ColumnName ="job_num")]
		public string JobNum { get; set; }

		/// <summary>
		/// 所属机构id
		/// </summary>
		[SugarColumn(ColumnName ="org_id")]
		public long OrgId { get; set; }

		/// <summary>
		/// 所属机构名称
		/// </summary>
		[SugarColumn(ColumnName ="org_name")]
		public string OrgName { get; set; }

	}

}
