//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 文件信息表
	/// </summary>
	[SugarTable("sys_file_info")]
	public class SysFileInfo {

		/// <summary>
		/// 主键id
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public long Id { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[SugarColumn(ColumnName ="create_time")]
		public DateTime? CreateTime { get; set; }

		/// <summary>
		/// 创建用户
		/// </summary>
		[SugarColumn(ColumnName ="create_user")]
		public long? CreateUser { get; set; }

		/// <summary>
		/// 文件仓库
		/// </summary>
		[SugarColumn(ColumnName ="file_bucket")]
		public string FileBucket { get; set; }

		/// <summary>
		/// 文件存储位置（1:阿里云，2:腾讯云，3:minio，4:本地）
		/// </summary>
		[SugarColumn(ColumnName ="file_location")]
		public sbyte FileLocation { get; set; }

		/// <summary>
		/// 存储到bucket的名称（文件唯一标识id）
		/// </summary>
		[SugarColumn(ColumnName ="file_object_name")]
		public string FileObjectName { get; set; }

		/// <summary>
		/// 文件名称（上传时候的文件名）
		/// </summary>
		[SugarColumn(ColumnName ="file_origin_name")]
		public string FileOriginName { get; set; }

		/// <summary>
		/// 存储路径
		/// </summary>
		[SugarColumn(ColumnName ="file_path")]
		public string FilePath { get; set; }

		/// <summary>
		/// 文件大小信息，计算后的
		/// </summary>
		[SugarColumn(ColumnName ="file_size_info")]
		public string FileSizeInfo { get; set; }

		/// <summary>
		/// 文件大小kb
		/// </summary>
		[SugarColumn(ColumnName ="file_size_kb")]
		public long? FileSizeKb { get; set; }

		/// <summary>
		/// 文件后缀
		/// </summary>
		[SugarColumn(ColumnName ="file_suffix")]
		public string FileSuffix { get; set; }

		/// <summary>
		/// 修改时间
		/// </summary>
		[SugarColumn(ColumnName ="update_time")]
		public DateTime? UpdateTime { get; set; }

		/// <summary>
		/// 修改用户
		/// </summary>
		[SugarColumn(ColumnName ="update_user")]
		public long? UpdateUser { get; set; }

	}

}
