//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 系统菜单表
	/// </summary>
	[SugarTable("sys_menu")]
	public class SysMenuInfo {

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public long Id { get; set; }

		/// <summary>
		/// 应用分类（应用编码）
		/// </summary>
		[SugarColumn(ColumnName ="application")]
		public string Application { get; set; }

		/// <summary>
		/// 编码
		/// </summary>
		[SugarColumn(ColumnName ="code")]
		public string Code { get; set; }

		/// <summary>
		/// 组件地址
		/// </summary>
		[SugarColumn(ColumnName ="component")]
		public string Component { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[SugarColumn(ColumnName ="create_time")]
		public DateTime? CreateTime { get; set; }

		/// <summary>
		/// 创建人
		/// </summary>
		[SugarColumn(ColumnName ="create_user")]
		public long? CreateUser { get; set; }

		/// <summary>
		/// 图标
		/// </summary>
		[SugarColumn(ColumnName ="icon")]
		public string Icon { get; set; }

		/// <summary>
		/// 链接地址
		/// </summary>
		[SugarColumn(ColumnName ="link")]
		public string Link { get; set; }

		/// <summary>
		/// 名称
		/// </summary>
		[SugarColumn(ColumnName ="name")]
		public string Name { get; set; }

		/// <summary>
		/// 打开方式（字典 0无 1组件 2内链 3外链）
		/// </summary>
		[SugarColumn(ColumnName ="open_type")]
		public sbyte OpenType { get; set; }

		/// <summary>
		/// 权限标识
		/// </summary>
		[SugarColumn(ColumnName ="permission")]
		public string Permission { get; set; }

		/// <summary>
		/// 父id
		/// </summary>
		[SugarColumn(ColumnName ="pid")]
		public long Pid { get; set; }

		/// <summary>
		/// 父ids
		/// </summary>
		[SugarColumn(ColumnName ="pids")]
		public string Pids { get; set; }

		/// <summary>
		/// 重定向地址
		/// </summary>
		[SugarColumn(ColumnName ="redirect")]
		public string Redirect { get; set; }

		/// <summary>
		/// 备注
		/// </summary>
		[SugarColumn(ColumnName ="remark")]
		public string Remark { get; set; }

		/// <summary>
		/// 路由地址
		/// </summary>
		[SugarColumn(ColumnName ="router")]
		public string Router { get; set; }

		/// <summary>
		/// 排序
		/// </summary>
		[SugarColumn(ColumnName ="sort")]
		public int Sort { get; set; }

		/// <summary>
		/// 状态（字典 0正常 1停用 2删除）
		/// </summary>
		[SugarColumn(ColumnName ="status")]
		public sbyte Status { get; set; }

		/// <summary>
		/// 菜单类型（字典 0目录 1菜单 2按钮）
		/// </summary>
		[SugarColumn(ColumnName ="type")]
		public sbyte Type { get; set; }

		/// <summary>
		/// 修改时间
		/// </summary>
		[SugarColumn(ColumnName ="update_time")]
		public DateTime? UpdateTime { get; set; }

		/// <summary>
		/// 修改人
		/// </summary>
		[SugarColumn(ColumnName ="update_user")]
		public long? UpdateUser { get; set; }

		/// <summary>
		/// 是否可见（Y-是，N-否）
		/// </summary>
		[SugarColumn(ColumnName ="visible")]
		public string Visible { get; set; }

		/// <summary>
		/// 权重（字典 1系统权重 2业务权重）
		/// </summary>
		[SugarColumn(ColumnName ="weight")]
		public sbyte? Weight { get; set; }

	}

}
