//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 通知表
	/// </summary>
	[SugarTable("sys_notice")]
	public class SysNoticeInfo {

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public long Id { get; set; }

		/// <summary>
		/// 撤回时间
		/// </summary>
		[SugarColumn(ColumnName ="cancel_time")]
		public DateTime? CancelTime { get; set; }

		/// <summary>
		/// 内容
		/// </summary>
		[SugarColumn(ColumnName ="content")]
		public string Content { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[SugarColumn(ColumnName ="create_time")]
		public DateTime? CreateTime { get; set; }

		/// <summary>
		/// 创建人
		/// </summary>
		[SugarColumn(ColumnName ="create_user")]
		public long? CreateUser { get; set; }

		/// <summary>
		/// 发布机构id
		/// </summary>
		[SugarColumn(ColumnName ="public_org_id")]
		public long? PublicOrgId { get; set; }

		/// <summary>
		/// 发布机构名称
		/// </summary>
		[SugarColumn(ColumnName ="public_org_name")]
		public string PublicOrgName { get; set; }

		/// <summary>
		/// 发布时间
		/// </summary>
		[SugarColumn(ColumnName ="public_time")]
		public DateTime? PublicTime { get; set; }

		/// <summary>
		/// 发布人id
		/// </summary>
		[SugarColumn(ColumnName ="public_user_id")]
		public long PublicUserId { get; set; }

		/// <summary>
		/// 发布人姓名
		/// </summary>
		[SugarColumn(ColumnName ="public_user_name")]
		public string PublicUserName { get; set; }

		/// <summary>
		/// 状态（字典 0草稿 1发布 2撤回 3删除）
		/// </summary>
		[SugarColumn(ColumnName ="status")]
		public sbyte Status { get; set; }

		/// <summary>
		/// 标题
		/// </summary>
		[SugarColumn(ColumnName ="title")]
		public string Title { get; set; }

		/// <summary>
		/// 类型（字典 1通知 2公告）
		/// </summary>
		[SugarColumn(ColumnName ="type")]
		public sbyte Type { get; set; }

		/// <summary>
		/// 修改时间
		/// </summary>
		[SugarColumn(ColumnName ="update_time")]
		public DateTime? UpdateTime { get; set; }

		/// <summary>
		/// 修改人
		/// </summary>
		[SugarColumn(ColumnName ="update_user")]
		public long? UpdateUser { get; set; }

	}

}
