//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 系统用户数据范围表
	/// </summary>
	[SugarTable("sys_notice_user")]
	public class SysNoticeUserInfo {

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public long Id { get; set; }

		/// <summary>
		/// 通知公告id
		/// </summary>
		[SugarColumn(ColumnName ="notice_id")]
		public long NoticeId { get; set; }

		/// <summary>
		/// 阅读时间
		/// </summary>
		[SugarColumn(ColumnName ="read_time")]
		public DateTime? ReadTime { get; set; }

		/// <summary>
		/// 状态（字典 0未读 1已读）
		/// </summary>
		[SugarColumn(ColumnName ="status")]
		public sbyte Status { get; set; }

		/// <summary>
		/// 用户id
		/// </summary>
		[SugarColumn(ColumnName ="user_id")]
		public long UserId { get; set; }

	}

}
