//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 系统操作日志表
	/// </summary>
	[SugarTable("sys_op_log")]
	public class SysOpLogInfo {

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public long Id { get; set; }

		/// <summary>
		/// 操作账号
		/// </summary>
		[SugarColumn(ColumnName ="account")]
		public string Account { get; set; }

		/// <summary>
		/// 浏览器
		/// </summary>
		[SugarColumn(ColumnName ="browser")]
		public string Browser { get; set; }

		/// <summary>
		/// 类名称
		/// </summary>
		[SugarColumn(ColumnName ="class_name")]
		public string ClassName { get; set; }

		/// <summary>
		/// ip
		/// </summary>
		[SugarColumn(ColumnName ="ip")]
		public string Ip { get; set; }

		/// <summary>
		/// 地址
		/// </summary>
		[SugarColumn(ColumnName ="location")]
		public string Location { get; set; }

		/// <summary>
		/// 具体消息
		/// </summary>
		[SugarColumn(ColumnName ="message")]
		public string Message { get; set; }

		/// <summary>
		/// 方法名称
		/// </summary>
		[SugarColumn(ColumnName ="method_name")]
		public string MethodName { get; set; }

		/// <summary>
		/// 名称
		/// </summary>
		[SugarColumn(ColumnName ="name")]
		public string Name { get; set; }

		/// <summary>
		/// 操作时间
		/// </summary>
		[SugarColumn(ColumnName ="op_time")]
		public DateTime? OpTime { get; set; }

		/// <summary>
		/// 操作类型
		/// </summary>
		[SugarColumn(ColumnName ="op_type")]
		public sbyte? OpType { get; set; }

		/// <summary>
		/// 操作系统
		/// </summary>
		[SugarColumn(ColumnName ="os")]
		public string Os { get; set; }

		/// <summary>
		/// 请求参数
		/// </summary>
		[SugarColumn(ColumnName ="param")]
		public string Param { get; set; }

		/// <summary>
		/// 请求方式（GET POST PUT DELETE)
		/// </summary>
		[SugarColumn(ColumnName ="req_method")]
		public string ReqMethod { get; set; }

		/// <summary>
		/// 返回结果
		/// </summary>
		[SugarColumn(ColumnName ="result")]
		public string Result { get; set; }

		/// <summary>
		/// 是否执行成功（Y-是，N-否）
		/// </summary>
		[SugarColumn(ColumnName ="success")]
		public string Success { get; set; }

		/// <summary>
		/// 请求地址
		/// </summary>
		[SugarColumn(ColumnName ="url")]
		public string Url { get; set; }

	}

}
