//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 第三方认证用户信息表
	/// </summary>
	[SugarTable("sys_oauth_user")]
	public class SysOauthUserInfo {

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public long Id { get; set; }

		/// <summary>
		/// 用户授权的token
		/// </summary>
		[SugarColumn(ColumnName ="access_token")]
		public string AccessToken { get; set; }

		/// <summary>
		/// 头像
		/// </summary>
		[SugarColumn(ColumnName ="avatar")]
		public string Avatar { get; set; }

		/// <summary>
		/// 用户网址
		/// </summary>
		[SugarColumn(ColumnName ="blog")]
		public string Blog { get; set; }

		/// <summary>
		/// 所在公司
		/// </summary>
		[SugarColumn(ColumnName ="company")]
		public string Company { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[SugarColumn(ColumnName ="create_time")]
		public DateTime? CreateTime { get; set; }

		/// <summary>
		/// 创建用户
		/// </summary>
		[SugarColumn(ColumnName ="create_user")]
		public long? CreateUser { get; set; }

		/// <summary>
		/// 邮箱
		/// </summary>
		[SugarColumn(ColumnName ="email")]
		public string Email { get; set; }

		/// <summary>
		/// 性别
		/// </summary>
		[SugarColumn(ColumnName ="gender")]
		public string Gender { get; set; }

		/// <summary>
		/// 位置
		/// </summary>
		[SugarColumn(ColumnName ="location")]
		public string Location { get; set; }

		/// <summary>
		/// 昵称
		/// </summary>
		[SugarColumn(ColumnName ="nick_name")]
		public string NickName { get; set; }

		/// <summary>
		/// 用户备注（各平台中的用户个人介绍）
		/// </summary>
		[SugarColumn(ColumnName ="remark")]
		public string Remark { get; set; }

		/// <summary>
		/// 用户来源
		/// </summary>
		[SugarColumn(ColumnName ="source")]
		public string Source { get; set; }

		/// <summary>
		/// 更新时间
		/// </summary>
		[SugarColumn(ColumnName ="update_time")]
		public DateTime? UpdateTime { get; set; }

		/// <summary>
		/// 更新用户
		/// </summary>
		[SugarColumn(ColumnName ="update_user")]
		public long? UpdateUser { get; set; }

		/// <summary>
		/// 第三方平台的用户唯一id
		/// </summary>
		[SugarColumn(ColumnName ="uuid")]
		public string Uuid { get; set; }

	}

}
