//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 系统角色表
	/// </summary>
	[SugarTable("sys_role")]
	public class SysRoleInfo {

		/// <summary>
		/// 主键id
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public long Id { get; set; }

		/// <summary>
		/// 编码
		/// </summary>
		[SugarColumn(ColumnName ="code")]
		public string Code { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[SugarColumn(ColumnName ="create_time")]
		public DateTime? CreateTime { get; set; }

		/// <summary>
		/// 创建人
		/// </summary>
		[SugarColumn(ColumnName ="create_user")]
		public long? CreateUser { get; set; }

		/// <summary>
		/// 数据范围类型（字典 1全部数据 2本部门及以下数据 3本部门数据 4仅本人数据 5自定义数据）
		/// </summary>
		[SugarColumn(ColumnName ="data_scope_type")]
		public sbyte DataScopeType { get; set; }

		/// <summary>
		/// 名称
		/// </summary>
		[SugarColumn(ColumnName ="name")]
		public string Name { get; set; }

		/// <summary>
		/// 备注
		/// </summary>
		[SugarColumn(ColumnName ="remark")]
		public string Remark { get; set; }

		/// <summary>
		/// 序号
		/// </summary>
		[SugarColumn(ColumnName ="sort")]
		public int Sort { get; set; }

		/// <summary>
		/// 状态（字典 0正常 1停用 2删除）
		/// </summary>
		[SugarColumn(ColumnName ="status")]
		public sbyte Status { get; set; }

		/// <summary>
		/// 更新时间
		/// </summary>
		[SugarColumn(ColumnName ="update_time")]
		public DateTime? UpdateTime { get; set; }

		/// <summary>
		/// 更新人
		/// </summary>
		[SugarColumn(ColumnName ="update_user")]
		public long? UpdateUser { get; set; }

	}

}
