//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 系统角色菜单表
	/// </summary>
	[SugarTable("sys_role_menu")]
	public class SysRoleMenuInfo {

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public long Id { get; set; }

		/// <summary>
		/// 菜单id
		/// </summary>
		[SugarColumn(ColumnName ="menu_id")]
		public long MenuId { get; set; }

		/// <summary>
		/// 角色id
		/// </summary>
		[SugarColumn(ColumnName ="role_id")]
		public long RoleId { get; set; }

	}

}
