//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 短信信息发送表
	/// </summary>
	[SugarTable("sys_sms")]
	public class SysSmsInfo {

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public long Id { get; set; }

		/// <summary>
		/// 回执id，可根据该id查询具体的发送状态
		/// </summary>
		[SugarColumn(ColumnName ="biz_id")]
		public string BizId { get; set; }

		/// <summary>
		/// 创建时间
		/// </summary>
		[SugarColumn(ColumnName ="create_time")]
		public DateTime? CreateTime { get; set; }

		/// <summary>
		/// 创建人
		/// </summary>
		[SugarColumn(ColumnName ="create_user")]
		public long? CreateUser { get; set; }

		/// <summary>
		/// 失效时间
		/// </summary>
		[SugarColumn(ColumnName ="invalid_time")]
		public DateTime? InvalidTime { get; set; }

		/// <summary>
		/// 手机号
		/// </summary>
		[SugarColumn(ColumnName ="phone_numbers")]
		public string PhoneNumbers { get; set; }

		/// <summary>
		/// 来源（字典 1 app， 2 pc， 3 其他）
		/// </summary>
		[SugarColumn(ColumnName ="source")]
		public sbyte Source { get; set; }

		/// <summary>
		/// 发送状态（字典 0 未发送，1 发送成功，2 发送失败，3 失效）
		/// </summary>
		[SugarColumn(ColumnName ="status")]
		public sbyte Status { get; set; }

		/// <summary>
		/// 短信模板ID
		/// </summary>
		[SugarColumn(ColumnName ="template_code")]
		public string TemplateCode { get; set; }

		/// <summary>
		/// 更新时间
		/// </summary>
		[SugarColumn(ColumnName ="update_time")]
		public DateTime? UpdateTime { get; set; }

		/// <summary>
		/// 更新人
		/// </summary>
		[SugarColumn(ColumnName ="update_user")]
		public long? UpdateUser { get; set; }

		/// <summary>
		/// 短信验证码
		/// </summary>
		[SugarColumn(ColumnName ="validate_code")]
		public string ValidateCode { get; set; }

	}

}
