//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//     Website: http://www.freesql.net
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------
using SqlSugar;
using System;

namespace Findx.Module.Admin.Models {

	/// <summary>
	/// 系统访问日志表
	/// </summary>
	[SugarTable("sys_vis_log")]
	public class SysVisLogInfo {

		/// <summary>
		/// 主键
		/// </summary>
		[SugarColumn(IsPrimaryKey = true, IsIdentity = false, ColumnName = "id")]
		public long Id { get; set; }

		/// <summary>
		/// 访问账号
		/// </summary>
		[SugarColumn(ColumnName ="account")]
		public string Account { get; set; }

		/// <summary>
		/// 浏览器
		/// </summary>
		[SugarColumn(ColumnName ="browser")]
		public string Browser { get; set; }

		/// <summary>
		/// ip
		/// </summary>
		[SugarColumn(ColumnName ="ip")]
		public string Ip { get; set; }

		/// <summary>
		/// 地址
		/// </summary>
		[SugarColumn(ColumnName ="location")]
		public string Location { get; set; }

		/// <summary>
		/// 具体消息
		/// </summary>
		[SugarColumn(ColumnName ="message")]
		public string Message { get; set; }

		/// <summary>
		/// 名称
		/// </summary>
		[SugarColumn(ColumnName ="name")]
		public string Name { get; set; }

		/// <summary>
		/// 操作系统
		/// </summary>
		[SugarColumn(ColumnName ="os")]
		public string Os { get; set; }

		/// <summary>
		/// 是否执行成功（Y-是，N-否）
		/// </summary>
		[SugarColumn(ColumnName ="success")]
		public string Success { get; set; }

		/// <summary>
		/// 访问时间
		/// </summary>
		[SugarColumn(ColumnName ="vis_time")]
		public DateTime? VisTime { get; set; }

		/// <summary>
		/// 操作类型（字典 1登入 2登出）
		/// </summary>
		[SugarColumn(ColumnName ="vis_type")]
		public sbyte VisType { get; set; }

	}

}
